export const meta = {
  name: 'meridian-experience-overhaul',
  description: 'Phase 1c.2 HYBRID overhaul: design system + chart vocabulary + entity pages (Subject/Platform/Faculty) + faculty layer + re-skin 7 tabs, web+mobile',
  phases: [
    { title: 'Explore', detail: '3 design directions + faculty seed research, in parallel' },
    { title: 'Judge', detail: 'judge panel scores directions; synthesize ONE winning spec' },
    { title: 'Foundation', detail: 'modularize app.js/styles.css; tokens + components + chart vocab; faculty schema (sequential)' },
    { title: 'Surfaces', detail: '3 entity pages + 7 re-skinned tabs, file-partitioned (parallel)' },
    { title: 'Review', detail: 'multi-lens adversarial static review -> per-file fixes' },
    { title: 'Integrate', detail: 'assemble, verify load order + build_data totals, report' },
  ],
}

const SCRATCH = '/private/tmp/claude-501/-Users-sriramrk-Meridian/de0b5b5f-6f00-4764-b4e4-1f1a39e07117/scratchpad'
const SPEC = 'plans/EXPERIENCE_DESIGN_SPEC.md'   // winning spec, committed
const MANIFEST = SCRATCH + '/MODULE_MANIFEST.md' // module API for surfaces
const REPORT = SCRATCH + '/OVERHAUL_REPORT.md'   // final coordinator report

// ---- shared context blocks embedded in prompts (agents also read the real docs) ----
const PROJECT = `
PROJECT: Meridian — a vanilla, local-first, offline-first web app (NO framework, NO build step).
"IMDB x cross-platform tracker x do-next coach" for India's medical PG exam prep (NEET PG / INI-CET / FMGE).
It is the neutral meta-layer above the prep platforms (Marrow, Cerebellum, DocTutorials, PrepLadder, eGurukul).
Files today: index.html + styles.css (768 lines) + app.js (1,539 lines, single global scope) + generated data.js
(from build_data.py) + storage.js (the local-first Store seam). Read these before acting.`

const DATAMODEL = `
DATA MODEL (window.D, generated by build_data.py — NEVER fabricate data):
  D = { exam, captured, platforms[], tests, videos[], sources[], subjectStrength, reliability, methodology }
  platforms[] = { id, name, kind:"qbank", color, cls, subjects:[{subject, modules:[{id,name,mcqs,rating,priority,hyScore,...}]}], reliability? }
  D.sources[] = evidence registry ({id,type,title,publisher,url,captured,note}); every curated claim references source ids.
  D.subjectStrength = best-platform-per-subject (epistemic "directional", community reputation, sourced).
  D.reliability = iOS App-Store scorecard (epistemic "public-3p", dated, sourced).
  D.methodology = the 4 epistemic-label definitions + neutrality firewall text ("How we rate").
  Integrated qbanks: Marrow + Cerebellum (42,889 MCQs) + DocTutorials (13,202) = TOTAL 56,091 — MUST be preserved.
  PrepLadder + eGurukul appear in scorecard/reputation as platformId:null (ingest seam, not yet content sources).
  hyScore = within-subject MCQ-density (a PROXY, NOT measured exam yield) — always labelled "proxy".
  build_data.py has a SOURCE-INTEGRITY GUARD that aborts if any curated claim references an unknown source id — keep it intact.
  Run 'python3 build_data.py' to regenerate data.js; it prints "combined MCQs: 42889", DocTutorials 13202, "all source refs resolve".`

const RUBRIC = `
THREE STANDING RUBRICS (read the full docs in plans/: MOBILE_DESIGN_STANDARD.md, DATA_VISUAL_STANDARD.md, FACULTY_LAYER.md).
Measurable bars (auto-fail if missed):
A) MOBILE DENSITY (verify at 375x812): KPI/stat blocks = compact 2-col tile grid (3-col at >=414); >=6 KPI tiles above the
   fold on Overview; tile height ~84-104px (NOT ~230). Lists are ROWS not cards: 44-56px tall, 1px hairline dividers,
   iOS inset-grouped feel (one rounded container, internal hairlines) — NOT N floating cards. ONE sticky toolbar row
   (slim search + sort/filter icon-buttons -> bottom-sheet + pill toggles), not a stack of full-width inputs. At most ONE
   hero serif number per screen; all other numbers compact tabular 18-22px; labels 11-12px uppercase. Tap targets >=44px.
B) DATA/VIZ SUBSTANCE: show JUDGMENT not inventory (consensus high-yield, best-platform/faculty per subject, what-to-do-next,
   neutral reliability) — never just "how much content exists". DRAW RELATIONSHIPS not big single numerals. EVERY figure
   carries its epistemic label (measured | proxy | directional | public-3p) + its source + date. Methodology/"How we rate"
   surface stays reachable. NEUTRALITY FIREWALL: never fabricate; money never moves the score; aggregate-only.
   >=1 TRUE relational visualization per relevant surface (subject x platform heatmap / consensus / treemap-ranked-bars /
   sparklines / faculty career timeline) — not decorative; color encodes data (sequential=yield, categorical=platform).
C) FACULTY LAYER: D.faculty[] schema with career timeline (current->past->solo->superspecialty) + two ratings
   (profile votes gated by verifiedVia:"in-app-activity"; rolled-up video rating) — both "directional" now, seed only.
   Aggregate-only, community-sentiment framing, NEVER a "worst faculty" board. Every name/affiliation/date/score sourced.`

const BRAND = `
BRAND IDENTITY (RETAIN — do not redesign to generic, never neon):
Warm editorial "almanac": paper/ink palette, serif DISPLAY face, hairline rules, muted clinical accents, calm + considered.
Existing CSS tokens (extend, don't replace the feel): --paper #f4f1ea / --paper-2 #fbf9f3 / --paper-3 #f0ece2;
--ink #23201b (+ ink-2/3/4 greys); --line #e4ddcf; --accent #1f4a3f (deep clinical pine); platform hues --marrow #3a5a78,
--cere #b0613b, --core #5d7a52; --gold #a9832f (high-yield + ratings); --bad #9a3b34 (oxblood). Evening theme (body.evening)
warm dusk, must keep working. Serif: Iowan/Palatino/Georgia stack; Sans: system. Tabular numerals everywhere data aligns.
The job: keep this soul while reaching the density of a native data app (Apple Health / Oura / Groww / Kite) and adding a
true chart vocabulary. Density via layout + type-scale + grouping, NOT by changing the brand.`

const ARCH = `
TARGET MODULE ARCHITECTURE (plain global-scope <script> files in dependency order — STILL no bundler, no ES modules,
no import/export; everything stays on window/global scope exactly like today). index.html load order:
  data.js, storage.js  (existing — keep)
  js/core.js     — shared seam: D alias, helpers ($ $$ el esc fmt pct), CANON/canon, PYQ, platform helpers
                   (PLATFORMS/QBANKS/platName/platCls/platColor/...), freshSubjects, LEAVES index + LEAF_BY_ID,
                   subjectsOf/subjMeta/leavesOf/treeOf, rollup/rollupLeaves, priStars/hyBadge, curation helpers
                   (CUR/SRC_BY_ID/EPI_DEF/epiBadge/epiName/epiDesc/srcLink/srcLinks/srcLine/platRefChip), token helpers,
                   cross-matching (STOP/toksC/sim/scoredCross/crossMatches/bestCross/bestCrossByPlat/siblings),
                   buildTests/relatedTests, NEW faculty helpers (FACULTY index, facById, facultyForSubject,
                   facultyForPlatform, videoFaculty rollup).
  js/ds.js       — shared COMPONENT + CHART library (pure functions returning HTML/SVG strings): statTile, listRow,
                   segmented, panel, chartFrame(title,epistemicTag,sourceIds), bottomSheet helpers, epistemic badge re-export;
                   CHART VOCABULARY: heatmap(subject x platform coverage/yield), consensusMark, treemap/rankedBars,
                   sparkline/smallMultiples, facultyTimeline, ratingScorecard. Charts live HERE (shared) — surfaces consume.
  js/surfaces/{overview,qbank,progress,tests,hy,videos,planner}.js — one renderX() per tab (move existing code here).
  js/entities/{subject,platform,faculty}.js — NEW: renderSubjectPage(canon)/renderPlatformPage(id)/renderFacultyPage(id).
  js/main.js     — RENDER map, TAB_ORDER/TAB_LABEL, show(view), ENTITY routing (goSubject/goPlatform/goFaculty into
                   #view-subject/#view-platform/#view-faculty), appClick delegation, nav/palette/drawer/sheet wiring,
                   wireToolbar/wireMobileChrome/wireDrawerDrag, toast, toggleTheme, keyboard, init(). Loads LAST.
CSS mirrors this: css/tokens.css, css/components.css, css/charts.css (foundation owns) + css/<surface>.css per surface.
index.html gets <section id="view-subject">, #view-platform, #view-faculty containers + the new <link>/<script> tags.
Old app.js + styles.css are REMOVED once fully split (their content lives in the modules).`

const HARD = `
HARD CONSTRAINTS (auto-fail): NEUTRALITY FIREWALL (epistemic label + source on every datum; NEVER fabricate a count/
rating/name/date; keep build_data.py guard; faculty aggregate-only, no "worst faculty"). Mobile density bars met.
NO horizontal scroll 320-1920. Console CLEAN. Local-first still works (storage.js Store seam untouched; no network deps).
Almanac identity retained (warm, never neon). TOTAL 56,091 preserved. Vanilla: no framework, no bundler, no ES-module
import/export, no new runtime deps. Validate JS syntax with 'node --check <file>' before finishing.`

const DESIGN_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['name', 'oneLiner', 'summary', 'wrote'],
  properties: {
    name: { type: 'string', description: 'name of this design direction' },
    oneLiner: { type: 'string', description: 'one-sentence essence' },
    summary: { type: 'string', description: '4-8 sentence summary of the direction and why it serves the rubrics' },
    wrote: { type: 'boolean', description: 'true if you wrote the full spec markdown file' },
  },
}

const JUDGE_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['scores', 'topPick', 'rationale', 'stealFrom'],
  properties: {
    scores: {
      type: 'array',
      description: 'one entry per design direction (A,B,C)',
      items: {
        type: 'object', additionalProperties: false,
        required: ['direction', 'density', 'dataViz', 'faculty', 'brand', 'feasibility', 'total'],
        properties: {
          direction: { type: 'string' },
          density: { type: 'number' }, dataViz: { type: 'number' }, faculty: { type: 'number' },
          brand: { type: 'number' }, feasibility: { type: 'number' }, total: { type: 'number' },
        },
      },
    },
    topPick: { type: 'string', description: 'A, B, or C' },
    rationale: { type: 'string' },
    stealFrom: { type: 'string', description: 'best ideas from the non-winning directions worth grafting in' },
  },
}

const REVIEW_SCHEMA = {
  type: 'object', additionalProperties: false, required: ['findings'],
  properties: {
    findings: {
      type: 'array',
      items: {
        type: 'object', additionalProperties: false,
        required: ['lens', 'severity', 'file', 'issue', 'fix'],
        properties: {
          lens: { type: 'string' },
          severity: { type: 'string', enum: ['high', 'med', 'low'] },
          file: { type: 'string', description: 'repo-relative path of the file to fix' },
          issue: { type: 'string' },
          fix: { type: 'string', description: 'concrete suggested fix' },
        },
      },
    },
  },
}

// ============================================================ Stage 1 — Explore
phase('Explore')

const DIRECTIONS = [
  { key: 'A', angle: 'EDITORIAL-ALMANAC MAXIMALIST — lean hard into the warm paper/serif identity; charts rendered as engraved/printed "almanac plates" (hairline-ruled, ink-on-paper), high-yield in antique gold. The data app that reads like a beautifully typeset reference annual. Risk to avoid: too precious / not dense enough — you must still hit every mobile-density bar.' },
  { key: 'B', angle: 'CLINICAL DATA-INSTRUMENT — Bloomberg/terminal-grade density and precision (Kite/Groww/Oura), tabular everything, charts as exact instruments with tight gridlines and small-multiples. Maximum information-at-a-glance. Risk to avoid: going cold/neon/generic-dashboard — you must keep the warm almanac soul and never use neon.' },
  { key: 'C', angle: 'RELATIONAL / IMDB-ENTITY — foreground the graph: entities (Subject, Platform, Faculty) and the relationships between them are the hero (who teaches what where, consensus across platforms, career movement). Cross-links everywhere, the heatmap/consensus/timeline are central. Risk to avoid: relationship-viz that is decorative not informative, or that buries the daily tracking density.' },
]

const designThunks = DIRECTIONS.map(d => () => agent(
  `${PROJECT}\n${DATAMODEL}\n${RUBRIC}\n${BRAND}\n${ARCH}\n\n` +
  `YOU ARE DESIGN DIRECTION ${d.key}. Produce ONE complete, concrete, cross-surface DESIGN DIRECTION for the Meridian ` +
  `Experience Overhaul (HYBRID ambition: keep the 7 tracking tabs as home, ADD first-class entity pages Subject/Platform/` +
  `Faculty, one design system with TWO layouts — desktop uses width/multi-panel, mobile uses density).\n\n` +
  `YOUR DISTINCT ANGLE: ${d.angle}\n\n` +
  `First READ: index.html, styles.css, app.js (skim structure), build_data.py, and the three rubric docs in plans/. ` +
  `Then design. Be CONCRETE and buildable in vanilla JS/CSS (HTML/SVG strings), not abstract mood-boarding.\n\n` +
  `Write your full spec to ${SCRATCH}/design_${d.key}.md covering ALL of:\n` +
  `1. VISUAL LANGUAGE — exact token additions/changes (extend the existing --paper/--ink/--accent/--gold tokens; give hex/` +
  `clamp values), type scale (display serif + tabular sans steps with px), spacing/radii/elevation, COLOR-AS-DATA-ENCODING ` +
  `(categorical platform palette Marrow/Cere/Doc/PrepL/eGuru; sequential yield/density ramp; semantic status) — never neon.\n` +
  `2. COMPONENT INVENTORY — stat-tile, list-row, epistemic badge, source-link/platform-ref chip, segmented control, ` +
  `bottom-sheet, panel, chart-frame: describe markup + the density behavior at mobile vs desktop.\n` +
  `3. CHART VOCABULARY — for EACH (subject x platform heatmap, consensus indicator, treemap/ranked-bars, sparkline/` +
  `small-multiples, faculty career timeline, rating scorecard): the SVG/HTML approach, what data it binds, how it adapts to ` +
  `narrow mobile, and how its epistemic label + source are shown.\n` +
  `4. ENTITY-PAGE IA — wireframe (in words/ASCII) for Subject, Platform, Faculty pages on BOTH desktop (multi-panel, uses ` +
  `the width) and mobile (density). Subject: coverage+yield heatmap row, consensus high-yield topics, who-teaches-it-best ` +
  `(faculty+platform strength, directional/sourced), videos, your progress. Platform: reliability scorecard (public-3p, ` +
  `dated), coverage by subject, faculty roster, your tracking. Faculty: career timeline, the two ratings (directional), ` +
  `subjects taught, linked platforms.\n` +
  `5. TAB RE-SKIN — how each of the 7 tabs (Overview/QBank/Progress/Tests/High-Yield/Videos/Planner) adopts the system and ` +
  `where a relational viz earns its place; how navigation reaches the entity pages (click subject -> Subject page, etc).\n` +
  `6. TWO-LAYOUTS RULE — the breakpoint strategy that makes desktop "use the width" and mobile "hit density" from ONE system.\n` +
  `7. HOW IT PASSES each measurable bar (cite the specific numbers: >=6 KPI tiles above fold, 44-56px rows, one toolbar, etc).\n\n` +
  `${HARD}\n\nReturn the structured summary (your name, one-liner, 4-8 sentence summary, wrote=true).`,
  { label: `design:${d.key}`, phase: 'Explore', schema: DESIGN_SCHEMA, effort: 'high' }
))

const facultyThunk = () => agent(
  `${PROJECT}\n${DATAMODEL}\n\n` +
  `TASK: produce a SMALL, reputation-safe, FULLY-SOURCED faculty SEED for Meridian's new faculty layer. Read ` +
  `plans/FACULTY_LAYER.md (schema + guardrails) and plans/FACULTY_DATA_PASS_PROMPT.md first.\n\n` +
  `NEUTRALITY FIREWALL IS ABSOLUTE: every faculty name, subject, affiliation, platform, date, and any rating MUST trace to ` +
  `a real, public source URL that you record. If you cannot source a fact via web search, OMIT it. NEVER fabricate a name, ` +
  `a platform association, a movement, or a date. Quality over quantity — aim for ~8-12 well-known NEET-PG faculty with a ` +
  `clear PUBLIC presence (platform faculty/educator pages, public course marketing, YouTube/official bios). Aggregate-only, ` +
  `community-sentiment framing; NO ratings unless publicly sourced (leave score:null, status:"directional"); NO "worst" anything.\n\n` +
  `USE WEB SEARCH (WebSearch/WebFetch — load via ToolSearch if needed). For each faculty capture only what you can source: ` +
  `name, aka (search nicknames), canonical subjects (match the app's CANON subject names), current platform + role, and ` +
  `prior/solo/super-specialty affiliations ONLY where a source confirms them (approximate years flagged approximate). ` +
  `Map to D.platforms ids where the platform is one of: marrow, cerebellum, doctutorials, prepladder, egurukul (use ` +
  `platformId:null + a name for solo/super-specialty brands).\n\n` +
  `WRITE TWO FILES (valid JSON):\n` +
  `1. _raw/curated/faculty_seed.json — { "_comment": "...", "epistemic":"directional", "captured":"<today>", "faculty":[ ` +
  `{ id:"fac-<slug>", name, aka:[], subjects:[], affiliations:[{platformId, name?, role, subjects:[], from, to, status:` +
  `"current|past|solo|superspecialty"}], ratings:{ profile:{score:null,count:0,verifiedVia:"in-app-activity",status:` +
  `"directional"}, videoByPlatform:[{platformId,avg:null,n:0,status:"directional"}] }, bio:"<short, sourced>", sourceIds:[], ` +
  `epistemic:"directional" } ] }\n` +
  `2. _raw/curated/faculty_sources.json — { "sources":[ {id:"src-fac-<slug>", type, title, publisher, url, captured, note} ] } ` +
  `— these get APPENDED to D.sources[]; ids MUST be unique and NOT collide with existing src- ids in _raw/curated/sources.json. ` +
  `Every sourceIds entry referenced in faculty_seed.json MUST exist here (or already in sources.json) — the build guard enforces this.\n\n` +
  `If web search is unavailable or you cannot confidently source faculty, WRITE faculty_seed.json with an EMPTY faculty:[] ` +
  `array (still valid) and say so — an honest empty seed is correct; a fabricated one is an auto-fail.\n\n` +
  `Return: count of faculty seeded, their names, what you omitted and why, the files written, and any lowest-confidence rows.`,
  { label: 'faculty:seed', phase: 'Explore', model: 'sonnet', effort: 'medium' }
)

const exploreResults = await parallel([...designThunks, facultyThunk])
const designSummaries = exploreResults.slice(0, 3).filter(Boolean)
const facultyReport = exploreResults[3]
log(`Explore done: ${designSummaries.length}/3 design directions, faculty seed: ${facultyReport ? 'returned' : 'FAILED'}`)

// ============================================================ Stage 2 — Judge + synthesize
phase('Judge')

const judgeThunks = [1, 2, 3].map(n => () => agent(
  `${PROJECT}\n${RUBRIC}\n${BRAND}\n\n` +
  `You are JUDGE #${n} on a design panel. Three independent design directions for the Meridian Experience Overhaul are at ` +
  `${SCRATCH}/design_A.md, design_B.md, design_C.md. READ ALL THREE in full.\n\n` +
  `Score each direction 1-10 on: DENSITY (mobile bars), DATA-VIZ (judgment-not-inventory + true relational viz + epistemic ` +
  `labels/sourcing + neutrality), FACULTY (does the entity-page IA serve the people-pillar + career timeline + gated ratings), ` +
  `BRAND (keeps the warm almanac soul, never neon, retains identity), FEASIBILITY (buildable in vanilla JS/CSS with no bundler, ` +
  `realistic). total = sum. Be adversarial and specific — name concrete strengths/failures, not vibes. Pick a topPick (A/B/C) ` +
  `and list the best ideas worth STEALING from the non-winners. Independent judgment — do not assume the others agree.`,
  { label: `judge:${n}`, phase: 'Judge', schema: JUDGE_SCHEMA, effort: 'high' }
))
const verdicts = (await parallel(judgeThunks)).filter(Boolean)
const tally = {}
verdicts.forEach(v => { tally[v.topPick] = (tally[v.topPick] || 0) + 1 })
log(`Judges' topPicks: ${JSON.stringify(tally)}`)

const synthSummary = await agent(
  `${PROJECT}\n${DATAMODEL}\n${RUBRIC}\n${BRAND}\n${ARCH}\n\n` +
  `You are the LEAD DESIGNER. Synthesize ONE winning, buildable design specification for the Meridian Experience Overhaul.\n` +
  `Inputs to READ: the three directions at ${SCRATCH}/design_A.md, design_B.md, design_C.md, AND the judge verdicts below.\n` +
  `JUDGE VERDICTS (JSON): ${JSON.stringify(verdicts)}\n\n` +
  `Choose the strongest base direction and GRAFT IN the best ideas from the others (the judges' "stealFrom"). Resolve every ` +
  `conflict. The result must be a single coherent system that PASSES ALL THREE RUBRICS and keeps the warm almanac identity.\n\n` +
  `WRITE the definitive spec to ${SPEC} (this file is committed and is the contract for all builders). It MUST be concrete ` +
  `enough to implement directly and include: (1) the EXACT design tokens (CSS custom properties with values — extend the ` +
  `existing ones; give the categorical platform palette, the sequential yield/density ramp, semantic status colors, full ` +
  `type scale in px, spacing/radii/elevation); (2) the COMPONENT library API — for each component, the exact function name, ` +
  `signature, and returned markup (e.g. statTile({label,value,note,accent,spark})); (3) the CHART vocabulary — for each chart, ` +
  `the function name + signature + SVG/HTML approach + mobile adaptation + how the epistemic label+source render; (4) the ` +
  `entity-page layouts (desktop multi-panel + mobile density) for Subject/Platform/Faculty; (5) the per-tab re-skin direction ` +
  `for all 7 tabs incl. which relational viz each gets; (6) the breakpoint/two-layouts rules; (7) a short "definition of done" ` +
  `checklist per surface tied to the measurable bars.\n\n${HARD}\n\n` +
  `Return a 5-10 line summary of the winning system (which base, what you grafted, the headline token + component decisions).`,
  { label: 'synthesize', phase: 'Judge', effort: 'high' }
)
log(`Winning spec written to ${SPEC}`)

// ============================================================ Stage 3 — Foundation (sequential, the shared seam)
phase('Foundation')

const modularizeReport = await agent(
  `${PROJECT}\n${DATAMODEL}\n${ARCH}\n\n` +
  `STAGE 3a — MODULARIZE (mechanical, the app must stay 100% functionally identical and runnable after this step; this is a ` +
  `PURE refactor — no visual/behavior change yet). Split the monolithic app.js (1,539 lines, single global scope) and ` +
  `styles.css into the TARGET MODULE ARCHITECTURE above.\n\n` +
  `RULES:\n` +
  `- Everything stays GLOBAL scope (no import/export, no type="module"). Move each function/const to exactly ONE module; ` +
  `keep names identical so cross-references keep working. Get the LOAD ORDER right so top-level consts that depend on others ` +
  `are defined after their dependencies (core.js before ds.js before surfaces/entities before main.js).\n` +
  `- Create js/core.js, js/ds.js (can be a stub with the component/chart function SIGNATURES that 3b fills in — but it must ` +
  `load without error), js/surfaces/{overview,qbank,progress,tests,hy,videos,planner}.js, js/entities/{subject,platform,` +
  `faculty}.js (entity files can start as stub render functions that return a simple placeholder — 3b/surfaces fill them), ` +
  `js/main.js. Create css/{tokens,components,charts}.css (can start mostly empty) + css/<surface>.css per surface by ` +
  `splitting the existing styles.css rules to the surface they belong to (shared rules -> components.css/tokens.css).\n` +
  `- Rewrite index.html: replace the single app.js <script> and styles.css <link> with the ordered new <script>/<link> tags; ` +
  `ADD <section id="view-subject" class="view">, #view-platform, #view-faculty inside <main>; keep data.js+storage.js tags.\n` +
  `- DELETE the old app.js and styles.css once their content is fully moved (verify nothing is left behind).\n` +
  `- The RENDER map / show() / init() go in main.js (loads last). Add ENTITY ROUTING scaffolding: goSubject(canon), ` +
  `goPlatform(id), goFaculty(id) that render into the new view sections and show them (entity pages are NOT tabs).\n\n` +
  `VALIDATE: run 'node --check' on every js/*.js and js/**/*.js file (0 errors). Run 'python3 build_data.py' (still 56,091). ` +
  `Reason carefully that load order satisfies all top-level const dependencies and no symbol is defined twice.\n\n` +
  `WRITE ${MANIFEST} documenting: every module file, the exact list of functions/consts it exports to global scope, and the ` +
  `entity-routing entry points. Surface builders will rely on this.\n\n` +
  `Return: the file list created, old files deleted (y/n), node --check result, build_data total, and anything that needed a judgment call.`,
  { label: 'foundation:modularize', phase: 'Foundation', effort: 'high' }
)
log(`Modularize: ${String(modularizeReport).slice(0, 200)}`)

const dsReport = await agent(
  `${PROJECT}\n${DATAMODEL}\n${RUBRIC}\n${BRAND}\n${ARCH}\n\n` +
  `STAGE 3b — DESIGN-SYSTEM FOUNDATION. Build on the modularized structure (see ${MANIFEST}). Implement the WINNING SPEC ` +
  `at ${SPEC} — READ IT FULLY; it is the contract. Three jobs:\n\n` +
  `(1) TOKENS + SHARED CSS — implement the winning tokens in css/tokens.css (extend existing --paper/--ink/--accent/--gold; ` +
  `add the categorical platform palette, the sequential yield/density ramp, semantic status colors, type scale, spacing/radii/` +
  `elevation). Keep body.evening working for every new token. Put shared component styles in css/components.css and chart ` +
  `styles in css/charts.css. NEVER neon; keep the warm almanac feel.\n` +
  `(2) COMPONENT + CHART LIBRARY — implement js/ds.js per the spec's API: the components (statTile, listRow, segmented, panel, ` +
  `chartFrame, bottom-sheet helpers, epistemic badge) AND the full CHART VOCABULARY as pure functions returning HTML/SVG ` +
  `strings: subject x platform heatmap, consensus indicator, treemap/ranked-bars, sparkline/small-multiples, faculty career ` +
  `timeline, rating scorecard. Each chart adapts to narrow mobile and renders its epistemic label + source via chartFrame. ` +
  `These are SHARED — surfaces will call them; match the exact signatures the spec documents and UPDATE ${MANIFEST} with the ` +
  `final ds.js API (names + signatures + one-line usage) so surface builders bind correctly.\n` +
  `(3) FACULTY DATA + SCHEMA — wire D.faculty[] into build_data.py: load _raw/curated/faculty_seed.json + APPEND ` +
  `_raw/curated/faculty_sources.json entries into the sources registry (so the source-integrity guard still passes), and ` +
  `EXTEND the guard's _collect_refs to also validate faculty sourceIds. Map D.videos[].facultyId where a video's subject+topic ` +
  `confidently matches a seeded faculty (only where certain; else leave unset). Add the faculty helpers to js/core.js ` +
  `(FACULTY index, facById, facultyForSubject, facultyForPlatform). Implement a REAL renderFacultyPage(id) in ` +
  `js/entities/faculty.js using the career-timeline chart + the two directional ratings + subjects + linked platforms ` +
  `(this proves the schema end-to-end). If faculty_seed.json has an empty faculty:[] array, build a graceful empty-state ` +
  `faculty page + still wire the schema/helpers. Then run 'python3 build_data.py' — it MUST still print 56,091, DocTutorials ` +
  `13202, and "all source refs resolve" (now including faculty sources).\n\n` +
  `VALIDATE: node --check all js files; build_data.py green; reason that ds.js loads before surfaces and core before ds.\n` +
  `${HARD}\n\nReturn: tokens added, the final ds.js component+chart API (names+signatures), faculty count wired, ` +
  `videos mapped to faculty (count), build_data totals, and any issue surfaces should know about.`,
  { label: 'foundation:design-system', phase: 'Foundation', effort: 'high' }
)
log(`Design-system foundation done`)

// ============================================================ Stage 4 — Surfaces (parallel, file-partitioned)
phase('Surfaces')

const SURFACES = [
  { key: 'entity-subject', js: 'js/entities/subject.js', css: 'css/subject.css', fn: 'renderSubjectPage(canon)',
    brief: 'The Subject ENTITY PAGE. Hero: coverage + yield ACROSS platforms as a heatmap row (subject x platform, the ' +
    'cross-platform thesis made visual). Consensus high-yield topics (>=2 platforms agree, visually distinct). WHO TEACHES ' +
    'IT BEST: faculty + platform strength from D.subjectStrength + D.faculty (directional, sourced, community-reputation ' +
    'framing — never a Meridian verdict). Related videos. Your progress (sparkline/meter). Every figure epistemically ' +
    'labelled + sourced. Desktop = multi-panel using the width; mobile = density. Links out to Platform + Faculty pages.' },
  { key: 'entity-platform', js: 'js/entities/platform.js', css: 'css/platform.css', fn: 'renderPlatformPage(id)',
    brief: 'The Platform ENTITY PAGE. Reliability scorecard (D.reliability, public-3p, dated, per-row source + complaint ' +
    'themes). Coverage by subject (ranked bars / treemap of MCQ mass, proxy-labelled). Faculty roster (D.faculty whose ' +
    'affiliations include this platform). Your tracking on this platform. Epistemic labels + sources throughout. Desktop ' +
    'multi-panel; mobile density. Links to Subject + Faculty pages.' },
  { key: 'entity-faculty', js: 'js/entities/faculty.js', css: 'css/faculty.css', fn: 'renderFacultyPage(id)',
    brief: 'The Faculty ENTITY PAGE (the people-pillar moat). Foundation may have built a first version — POLISH it to the ' +
    'spec. Career TIMELINE (current -> past -> solo -> super-specialty) via the timeline chart. The TWO ratings (profile ' +
    'votes gated by verifiedVia; rolled-up video rating) shown as DIRECTIONAL seed only, clearly labelled, aggregate-only, ' +
    'community-sentiment framing — NEVER a worst-faculty board. Subjects taught; linked platforms (chips -> Platform page). ' +
    'Every datum sourced. Graceful empty-state if the seed is empty. Desktop + mobile layouts.' },
  { key: 'overview', js: 'js/surfaces/overview.js', css: 'css/overview.css', fn: 'renderOverview()',
    brief: 'HOME. Mobile: >=6 compact KPI tiles above the fold (2-col, 3-col >=414, ~84-104px each, tabular numerals, ' +
    'accent/spark) + start of next section. Desktop: use the width — multi-panel with at least one relational viz (the ' +
    'subject x platform heatmap and/or consensus). Surface JUDGMENT (best-platform-per-subject directional, the public-3p ' +
    'reliability scorecard, "How we rate / sources") not just counts. Everything labelled + sourced. Link tiles/rows out to ' +
    'entity pages.' },
  { key: 'qbank', js: 'js/surfaces/qbank.js', css: 'css/qbank.css', fn: 'renderQbank()',
    brief: 'QBank tracker. Mobile: ONE sticky toolbar row (slim search + sort/filter icon-buttons -> bottom-sheet + hi-yield ' +
    'pill + platform segmented control) then >=4 category/module ROWS (44-56px, hairline dividers, inset-grouped). Keep all ' +
    'existing tracking behavior (A/R/Rt toggles, cross-platform coverage, drawer). hyScore stays proxy-labelled. Subject ' +
    'names link to the Subject page; platform refs to the Platform page.' },
  { key: 'progress', js: 'js/surfaces/progress.js', css: 'css/progress.css', fn: 'renderProgress()',
    brief: 'Progress. Replace giant single numerals with sparklines / small-multiples per subject + compact meters. Show ' +
    'relationships (where you are weak vs high-yield). Density on mobile; multi-panel on desktop. Labels + sources where any ' +
    'curated figure appears.' },
  { key: 'tests', js: 'js/surfaces/tests.js', css: 'css/tests.css', fn: 'renderTests()',
    brief: 'Tests & Scores. Keep scoring/accuracy entry + per-subject accuracy. Use compact rows + a small relational/ ' +
    'small-multiples view of accuracy by subject. Mobile density; desktop width.' },
  { key: 'hy', js: 'js/surfaces/hy.js', css: 'css/hy.css', fn: 'renderHY()',
    brief: 'High-Yield. This is JUDGMENT surface #1: consensus (>=2 platforms agree) made visual, treemap/ranked-bars of ' +
    'MCQ-density mass (PROXY — must be labelled "MCQ density (proxy), not measured exam yield"), best-platform-per-subject ' +
    '(directional). Every figure labelled + sourced. Tab name stays "High-Yield" but badged proxy in-view. Relational viz ' +
    'is mandatory here. Links to Subject pages.' },
  { key: 'videos', js: 'js/surfaces/videos.js', css: 'css/videos.css', fn: 'renderVideos()',
    brief: 'Videos. Compact rows (watched/revised toggles preserved), grouped by subject. Where a video maps to a faculty ' +
    '(D.videos[].facultyId), link to the Faculty page. Mobile density; desktop width.' },
  { key: 'planner', js: 'js/surfaces/planner.js', css: 'css/planner.css', fn: 'renderPlanner()',
    brief: 'Study Planner. Do-next intelligence framed as judgment (untracked high-yield, weak subjects). Compact, dense, ' +
    'relational where it helps. Labels + sources on curated figures.' },
]

const surfaceResults = await parallel(SURFACES.map(s => () => agent(
  `${PROJECT}\n${DATAMODEL}\n${RUBRIC}\n${BRAND}\n\n` +
  `You implement ONE surface. You OWN exactly these files and may edit ONLY them: ${s.js} and ${s.css}. DO NOT edit any ` +
  `other file (not index.html, not core.js, not ds.js, not main.js, not other surfaces) — they are owned by others and ` +
  `concurrent edits will corrupt the build. If you need something missing from the shared layer, NOTE it in your return ` +
  `instead of editing shared files.\n\n` +
  `READ FIRST: the winning spec ${SPEC} (the contract), the module manifest ${MANIFEST} (the exact ds.js component/chart ` +
  `API + core helpers you must call), and the file you own. Use the SHARED components/charts from js/ds.js and helpers from ` +
  `js/core.js — do not reinvent or duplicate them.\n\n` +
  `SURFACE: ${s.key} — implement ${s.fn} in ${s.js} with styles in ${s.css}.\n` +
  `BRIEF: ${s.brief}\n\n` +
  `Meet the measurable bars for this surface (density on mobile, real relational viz where required, judgment-not-inventory, ` +
  `every datum epistemically labelled + sourced, no horizontal scroll, tap targets >=44px, warm almanac identity, never ` +
  `neon). Preserve all existing tracking behavior and data wiring. VALIDATE: run 'node --check ${s.js}' (0 errors).\n\n` +
  `${HARD}\n\nReturn: what you built, which ds.js charts/components you used, the relational viz present, and any shared-layer ` +
  `gap the integrator must resolve.`,
  { label: `surface:${s.key}`, phase: 'Surfaces', effort: 'high' }
)))
log(`Surfaces done: ${surfaceResults.filter(Boolean).length}/${SURFACES.length}`)

// ============================================================ Stage 5 — Adversarial review -> fix
phase('Review')

const LENSES = [
  { key: 'density', focus: 'MOBILE DENSITY bars (MOBILE_DESIGN_STANDARD.md). At 375px reasoning: >=6 KPI tiles above fold on ' +
    'Overview; rows 44-56px with hairline dividers (not fat one-datum cards); ONE toolbar row on QBank; at most one hero serif ' +
    'number per screen; tabular numerals; tap targets >=44px. Flag any anti-pattern.' },
  { key: 'neutrality', focus: 'NEUTRALITY/SOURCING (DATA_VISUAL_STANDARD.md + FACULTY_LAYER.md). EVERY on-screen figure must ' +
    'carry an epistemic label (measured/proxy/directional/public-3p) + source; no proxy shown as yield unbadged; no rating/rank ' +
    'without source+date; NO fabricated data; faculty aggregate-only with no "worst" framing. Cross-check claims against ' +
    '_raw/curated/*.json + RESEARCH_FINDINGS.md. This lens is auto-fail-critical.' },
  { key: 'mobile-native', focus: 'Does each surface FEEL like a native data app (Health/Kite) not a stacked website? ' +
    'inset-grouped lists, bottom-sheets, segmented controls, sticky compact chrome. Flag anything that reads as a webpage.' },
  { key: 'desktop-width', focus: 'Do desktop layouts USE THE WIDTH (multi-panel, relational viz) rather than stretching mobile ' +
    'cards across the page? Is there >=1 true relational visualization per relevant surface?' },
  { key: 'console-breakpoint', focus: 'Console-risk + breakpoint CSS: undefined globals, calls to ds.js/core.js functions with ' +
    'wrong signatures, missing null guards, CSS that would cause horizontal overflow at 320 or break at 1920, broken entity ' +
    'routing. Reason through load order (core->ds->surfaces->entities->main). Run node --check across js files and report errors.' },
  { key: 'consistency', focus: 'Cross-surface CONSISTENCY: do all surfaces use the same ds.js components/tokens (not bespoke ' +
    'one-offs)? Do entity links work both ways (subject<->platform<->faculty)? Is the warm almanac identity uniform, never neon?' },
]

const reviewResults = (await parallel(LENSES.map(L => () => agent(
  `${PROJECT}\n${DATAMODEL}\n${RUBRIC}\n${BRAND}\n\n` +
  `You are an ADVERSARIAL REVIEWER (read-only — do NOT edit files). LENS: ${L.key}.\n${L.focus}\n\n` +
  `Review the FULL assembled app: index.html, css/*.css, js/core.js, js/ds.js, js/surfaces/*.js, js/entities/*.js, js/main.js, ` +
  `and build_data.py + _raw/curated/*.json as relevant to your lens. Read the winning spec ${SPEC} as the intended contract. ` +
  `Be skeptical and specific; default to flagging a real problem over being generous. For each finding give the exact ` +
  `repo-relative file, the issue, and a concrete fix. Only report findings within your lens. Return the structured findings.`,
  { label: `review:${L.key}`, phase: 'Review', schema: REVIEW_SCHEMA, effort: 'high' }
)))).filter(Boolean)

const allFindings = reviewResults.flatMap(r => r.findings || []).filter(f => f.severity !== 'low')
// group actionable findings by target file -> one fix agent per file (no concurrent edits to same file)
const byFile = {}
allFindings.forEach(f => { (byFile[f.file] = byFile[f.file] || []).push(f) })
const fileList = Object.keys(byFile)
log(`Review: ${allFindings.length} actionable findings across ${fileList.length} files`)

const SHARED_FILES = new Set(['index.html', 'js/core.js', 'js/ds.js', 'js/main.js', 'build_data.py',
  'css/tokens.css', 'css/components.css', 'css/charts.css'])
const fixResults = await parallel(fileList.map(file => () => agent(
  `${PROJECT}\n${RUBRIC}\n${BRAND}\n\n` +
  `You are a FIX agent. Edit ONLY this one file: ${file}. Apply the fixes below (and only changes scoped to this file). Do ` +
  `not touch any other file. Preserve all working behavior and the data wiring; keep the neutrality firewall (labels+sources, ` +
  `no fabrication) and the warm almanac identity. ${SHARED_FILES.has(file) ? 'This is a SHARED file — be especially careful ' +
  'not to break global load order, symbol names, or build_data totals.' : ''}\n\n` +
  `FINDINGS for ${file} (JSON): ${JSON.stringify(byFile[file])}\n\n` +
  `After editing, if it is a .js file run 'node --check ${file}'; if it is build_data.py run 'python3 build_data.py' and ` +
  `confirm 56,091 + "all source refs resolve". Return what you changed and the validation result.`,
  { label: `fix:${file.split('/').pop()}`, phase: 'Review', effort: 'high' }
)))
log(`Fixes applied to ${fixResults.filter(Boolean).length}/${fileList.length} files`)

// ============================================================ Stage 6 — Integrate
phase('Integrate')

const integration = await agent(
  `${PROJECT}\n${DATAMODEL}\n${ARCH}\n\n` +
  `FINAL INTEGRATION + SELF-VERIFICATION (you may edit files to fix integration breakages only). Confirm the whole app ` +
  `assembles correctly:\n` +
  `1. index.html loads scripts in the correct dependency order (data.js, storage.js, js/core.js, js/ds.js, surfaces, ` +
  `entities, js/main.js) and all css <link>s are present; the #view-subject/#view-platform/#view-faculty containers exist.\n` +
  `2. No duplicate global symbol definitions across modules; every render function referenced by the RENDER map + entity ` +
  `routing exists. Old app.js + styles.css are gone.\n` +
  `3. Run 'node --check' on EVERY js file (js/*.js and js/**/*.js) — 0 errors. Fix any that fail.\n` +
  `4. Run 'python3 build_data.py' — MUST print "combined MCQs: 42889", DocTutorials 13202, faculty count, and "all source ` +
  `refs resolve". Fix if broken.\n` +
  `5. Grep for obvious console-risk patterns (calls to undefined fns, wrong-arity ds.js calls) and broken entity links.\n\n` +
  `Then WRITE the COORDINATOR REPORT to ${REPORT} (markdown) AND return a concise version. The report covers: per surface ` +
  `what shipped; the design-system tokens + ds.js component/chart API; faculty seed count + omissions; the relational viz ` +
  `built per surface; the final file inventory (js/ + css/); build_data totals; node --check status; and ANYTHING that needs ` +
  `a coordinator decision or that live-browser verification should focus on. Be honest about gaps — do not claim done where ` +
  `it is not.`,
  { label: 'integrate', phase: 'Integrate', effort: 'high' }
)

log('WORKFLOW COMPLETE. Design picks: ' + JSON.stringify(tally) + ' | surfaces built: ' +
  surfaceResults.filter(Boolean).length + '/' + SURFACES.length + ' | findings fixed across ' +
  fileList.length + ' files. Report at ' + REPORT)
log('INTEGRATION SUMMARY:\n' + String(integration))
